### ISSUE TITLE
Error in computing non-symmetric 3c2e integral slices

### ISSUE THREAD

**Issue by qjliang12** [pyscf/gpu4pyscf#279] opened 2024-12-11 14:04 UTC
I was trying to get a 3c2e df integral slice with the following code,
`from pyscf import gto, df
from gpu4pyscf.df.int3c2e import VHFOpt, get_int3c2e_slice

mol = gto.M(
    atom = '''O   0.00000 0.00000 0.11779
              H   0.00000 0.75545 -0.47116
              H   0.00000 -0.75545 -0.47116''',
    basis = '6-31g',
)
mol.build()

with_df = df.DF(mol)
auxmol = df.addons.make_auxmol(mol, with_df.auxbasis)

intopt = VHFOpt(mol, auxmol, 'int2e')
intopt.build(1e-13, diag_block_with_triu=True, aosym=False)

cp_ij_id = 3
cp_kl_id = 0

int_slice = get_int3c2e_slice(intopt, cp_ij_id, cp_kl_id)
print(int_slice.ravel())`

but got an error "roots=1 type_ijkl 4", and the output integral slice is an zero array. Could you take a look at this issue please? @sunqm @wxj6000 Thank you very much.

**Comment by qjliang12** [comment] 2024-12-11 14:29
FYI, my pyscf version is "2.7.0" and the gpu4pyscf version is "1.1.0" (compiled with CUDA 11.7).

**Comment by wxj6000** [comment] 2024-12-11 18:04
The issue is fixed in https://github.com/pyscf/gpu4pyscf/pull/280

**Closed** 2024-12-12 02:53 UTC
